apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-storageclass.yaml
  - 02-postgres-secret.yaml
  - 03-postgres-pvc.yaml
  - 04-postgres-deployment.yaml
  - 05-postgres-service.yaml
  - 06-redis-deployment.yaml
  - 07-redis-service.yaml
  - 08-vote-deployment.yaml
  - 09-vote-service.yaml
  - 10-worker-deployment.yaml
  - 11-result-deployment.yaml
  - 12-result-service.yaml
